### ISSUE TITLE
Portals are not visible

### ISSUE THREAD

**Issue by 0Calories** [ryantpayton/MapleStory-Client#19]
You can interact with portals on maps, but they cannot be seen visually

**Comment by ryantpayton** [comment]
@0Calories Portals were working, and I noticed this issue too. I believe this is due to the mix from my latest changes. I would take a look into `Stage::draw`, IIRC, and you should see portals being drawn/updated. You can debug real time and check the reference to the NX file. If it is 0x00000000000 it is NULL which means we are just referencing the WZ file locations incorrectly.
